// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJtjZEA_kPM2q-iiHA9ze8LLWwiU3xqZg',
    appId: '1:223334899075:web:9a02b9145e564566feeab6',
    messagingSenderId: '223334899075',
    projectId: 'data-management-8b1e9',
    authDomain: 'data-management-8b1e9.firebaseapp.com',
    storageBucket: 'data-management-8b1e9.appspot.com',
    measurementId: 'G-WMLLG8364C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6jhk4E1sGC1v6gJJ2mYI43RWnGTpvjxk',
    appId: '1:223334899075:android:9ce9216d9f75cc51feeab6',
    messagingSenderId: '223334899075',
    projectId: 'data-management-8b1e9',
    storageBucket: 'data-management-8b1e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNhAqVMz9D87Ju2VnRH1urDJv1KhqHVeU',
    appId: '1:223334899075:ios:152f27d6bea9858cfeeab6',
    messagingSenderId: '223334899075',
    projectId: 'data-management-8b1e9',
    storageBucket: 'data-management-8b1e9.appspot.com',
    iosBundleId: 'com.example.dataStorageManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNhAqVMz9D87Ju2VnRH1urDJv1KhqHVeU',
    appId: '1:223334899075:ios:152f27d6bea9858cfeeab6',
    messagingSenderId: '223334899075',
    projectId: 'data-management-8b1e9',
    storageBucket: 'data-management-8b1e9.appspot.com',
    iosBundleId: 'com.example.dataStorageManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJtjZEA_kPM2q-iiHA9ze8LLWwiU3xqZg',
    appId: '1:223334899075:web:cff97a6931b76cd3feeab6',
    messagingSenderId: '223334899075',
    projectId: 'data-management-8b1e9',
    authDomain: 'data-management-8b1e9.firebaseapp.com',
    storageBucket: 'data-management-8b1e9.appspot.com',
    measurementId: 'G-2T01V3NW6M',
  );
}
